platform :ios, "7.0"
pod 'MBProgressHUD', '~> 0.9.1'
pod 'FreeStreamer', '~> 2.12.5'
pod 'SDWebImage', '~> 3.7.2'
pod 'MKNetworkKit'
pod 'UIAlertView-Blocks'
pod 'DKCircleButton'
pod 'AFNetworking'
pod 'MJExtension'
pod 'REFrostedViewController', '~> 2.4.8'
pod 'RNFrostedSidebar', '~> 0.2.0'